version: 2
jobs:
  deploy:
    working_directory: ~/QlikResources
    docker:
      - image: microsoft/powershell:ubuntu-16.04
    steps:
      - checkout
      - run:
          name: Install module dependencies
          shell: /usr/bin/pwsh
          command: |
            $ProgressPreference = 'SilentlyContinue'
            (Import-LocalizedData -BaseDirectory (Get-Location).Path -FileName QlikResources.psd1).RequiredModules.ForEach({
              Install-Module -Name $_ -Force
            })
      - run:
          name: Check version has been incremented in manifest
          shell: /usr/bin/pwsh
          command: |
            if ((Test-ModuleManifest -Path ./QlikResources.psd1).Version -le (Find-Module -Name QlikResources).Version) {
              Write-Error "Module version must be newer than published version"
            }
      - run:
          name: Install .Net Core SDK
          command: |
            apt-get update
            apt-get install -y dotnet-sdk-2.1.4
      - run:
          name: Publish module to PowerShell Gallery
          shell: /usr/bin/pwsh
          command: Publish-Module -Path ./ -NuGetApiKey $env:PSG_API_KEY -Verbose

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
          context: powershell-gallery
