version: 2.1
executors:
  powershell:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1.410-focal
    shell: /usr/bin/pwsh

jobs:
  build:
    executor: powershell
    steps:
      - checkout
      - restore_cache:
          keys:
            - psm-cache-v1-{{ checksum "QlikResources.psd1" }}
      - run:
          name: Install Psake
          command: |
            if (!(Get-Module -Name Psake -ListAvailable)) {
              Install-Module -Name Psake -Force
            }
      - run:
          name: Install module dependencies
          command: |
            $ProgressPreference = 'SilentlyContinue'
            (Import-LocalizedData -BaseDirectory (Get-Location).Path -FileName QlikResources.psd1).RequiredModules.ForEach({
              if (!(Get-Module -Name $_ -ListAvailable)) {
                Write-Information "Installing $_" -InformationAction Continue
                Install-Module -Name $_ -Force
              }
            })
      - save_cache:
          key: psm-cache-v1-{{ checksum "QlikResources.psd1" }}
          paths:
            - /root/.local/share/powershell/Modules
      - run:
          name: Build
          command: |
            $ProgressPreference = 'SilentlyContinue'
            $ErrorActionPreference = 'Stop'
            Invoke-psake -taskList Package -parameters @{version="$($env:CIRCLE_TAG.Substring(1))"}
      - run:
          name: Check version is later than any published version
          command: |
            $ProgressPreference = 'SilentlyContinue'
            if ((Test-ModuleManifest -Path ./modules/QlikResources/QlikResources.psd1).Version -le (Find-Module -Name QlikResources).Version) {
              Write-Error "Module version must be newer than published version"
            }
      - persist_to_workspace:
          root: .
          paths:
            - modules/QlikResources
            - .package
      - store_artifacts:
          path: .package/QlikResources.zip
          destination: QlikResources.zip

  publish-powershell-gallery:
    working_directory: /workspace/modules/QlikResources
    executor: powershell
    steps:
      - attach_workspace:
          at: /workspace
      - restore_cache:
          keys:
            - psm-cache-v1-{{ checksum "QlikResources.psd1" }}
      - run:
          name: Publish module to PowerShell Gallery
          shell: /usr/bin/pwsh
          command: Publish-Module -Path ./ -NuGetApiKey $env:PSG_API_KEY -Verbose -ErrorAction Stop

  publish-github-release:
    working_directory: /workspace/QlikResources
    docker:
      - image: cibuilds/github:latest
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Publish release on GitHub
          command: |
            ghr -t ${GITHUB_TOKEN} \
                -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                -replace \
                ${CIRCLE_TAG} \
                /workspace/.package/QlikResources.zip

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-powershell-gallery:
          context: powershell-gallery
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - publish-github-release:
          context: github
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+.*/
